"""Second initial migration. Hard reset due to naming convention bug

Revision ID: 13455da48ced
Revises: 
Create Date: 2024-04-30 14:55:42.100898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13455da48ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pwd', sa.String(length=300), nullable=False),
    sa.Column('guessed', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word'))
    )
    op.create_table('sketch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sketch_path', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_sketch_user_id_user')),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name=op.f('fk_sketch_word_id_word')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sketch'))
    )
    op.create_table('guess_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sketch_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sketch_id'], ['sketch.id'], name=op.f('fk_guess_session_sketch_id_sketch')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_guess_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guess_session'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess_session')
    op.drop_table('sketch')
    op.drop_table('word')
    op.drop_table('user')
    # ### end Alembic commands ###
