"""empty message

Revision ID: 834477a15f24
Revises: 13455da48ced
Create Date: 2024-05-14 15:53:33.246271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834477a15f24'
down_revision = '13455da48ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('guess_correctly', sa.Boolean(), nullable=False))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('guess_correctly')
        batch_op.drop_column('guess_at')

    # ### end Alembic commands ###
